name: Release Binaries

on:
  push

jobs:

  build-binaries:

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Setup Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      
      - name: Setup Poetry ${{ vars.POETRY_VERSION }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry==${{ vars.POETRY_VERSION }}

      - name: Install depencencies
        run: poetry install --with prod
      
      - name: Create pyinstaller package
        run: poetry run pyinstaller --onefile mdPDFinator.py

      - name: Upload the binary
        uses: actions/upload-artifact@v3
        with:
          name: executable-${{ runner.os }}
          path: dist/mdPDFinator*
    
  test-binaries:

    needs: build-binaries
    
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2019]
    runs-on: ${{ matrix.os }}

    steps:

      - name: Install weasyprint (Linux)
        if: ${{ runner.os == 'Linux' }}
        run: sudo apt install weasyprint

      - name: Install weasyprint (macOS)
        if: ${{ runner.os == 'macOS' }}
        run: brew install weasyprint

      - name: Test it out
        run: |
          cd dist
          ./mdPDFinator ../.github/README.md

      - name: Upload the converted PDF file
        uses: actions/upload-artifact@v3
        with:
          name: test-output-${{ runner.os }}
          path: dist/output.pdf
