name: Release Binaries

on:
  push

jobs:

  linux:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Setup Python ${{ vars.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ vars.PYTHON_VERSION }}
      
      # - name: Setup Poetry ${{ vars.POETRY_VERSION }}
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install poetry==${{ vars.POETRY_VERSION }}

      - name: Setup Poetry ${{ vars.POETRY_VERSION }}
        uses: snok/install-poetry@v1
        with:
          version: ${{ vars.POETRY_VERSION }}
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install depencencies
        run: poetry install --with prod

      - name: List files before pyinstaller
        run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
      
      - name: Create pyinstaller package
        run: pyinstaller --onefile mdPDFinator.py

      - name: List files after pyinstaller
        run: find . | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"